
tilt_controller/Kp: 40
tilt_controller/Ki: 10
tilt_controller/Kd: 0.08
encoder_synch_controller/Kp: 10
encoder_synch_controller/Ki: 0
encoder_synch_controller/Kd: 0
velocity_controller/Kp: 0.4
velocity_controller/Ki: 0.0
velocity_controller/Kd: 0.00
position_controller/Kp: 35
position_controller/Ki: 20
position_controller/Kd: 10
pos/final_pos: 1

